#!/usr/bin/env node
'use strict';

// MeshCommander Fleet Telemetry Collector V0.1
// READ-ONLY sidecar. It calls MeshCtrl ListDevices --details --json and writes
// a compact JSON file under meshcentral-web/public. It does not modify the
// MeshCentral database, agents, config.json or node_modules.

const fs=require('fs'),path=require('path'),{execFile}=require('child_process');
const root=process.env.MESHCENTRAL_ROOT||'/home/administrator/meshcentral';
const meshctrl=process.env.MCT_MESHCTRL||path.join(root,'node_modules','meshcentral','meshctrl.js');
const output=process.env.MCT_OUTPUT||path.join(root,'meshcentral-web','public','meshcommander','v9-fleet.json');
function fail(m){console.error('[telemetry] ERROR:',m);process.exit(1);} function val(v){return v==null?'':String(v);} function auth(){const a=[];if(process.env.MCT_URL)a.push('--url',process.env.MCT_URL);if(process.env.MCT_USER)a.push('--loginuser',process.env.MCT_USER);if(process.env.MCT_LOGIN_KEY_FILE)a.push('--loginkeyfile',process.env.MCT_LOGIN_KEY_FILE);else if(process.env.MCT_PASS)a.push('--loginpass',process.env.MCT_PASS);if(process.env.MCT_DOMAIN)a.push('--domain',process.env.MCT_DOMAIN);return a;}
function call(){return new Promise((resolve,reject)=>execFile(process.execPath,[meshctrl,'listdevices','--details','--json'].concat(auth()),{timeout:15*60*1000,maxBuffer:256*1024*1024},(e,out,err)=>e?reject(new Error((err||e.message).trim())):resolve(out.trim())));}
function arrayOf(x){if(Array.isArray(x))return x;if(x&&typeof x==='object'){if(Array.isArray(x.devices))return x.devices;return Object.keys(x).map(k=>x[k]).filter(v=>v&&typeof v==='object');}return[];}
function idOf(d){return d&&val(d._id||d.id||d.nodeid||d.nodeId||d['Device ID']);}
function walk(obj,fn,depth){if(!obj||typeof obj!=='object'||depth>8)return;fn(obj);if(Array.isArray(obj)){obj.forEach(x=>walk(x,fn,depth+1));return;}Object.keys(obj).forEach(k=>{const v=obj[k];if(v&&typeof v==='object')walk(v,fn,depth+1);});}
function pickIdentity(d){let serial='',uuid='';walk(d,o=>{Object.keys(o).forEach(k=>{const l=k.toLowerCase().replace(/[^a-z]/g,'');if(!serial&&(l==='biosserial'||l==='serialnumber'||l==='biosserialnumber'))serial=val(o[k]);if(!uuid&&(l==='uuid'||l==='systemuuid'||l==='machineuuid'))uuid=val(o[k]);});},0);return{biosSerial:serial,uuid:uuid};}
function encryption(d){let seen=false,encrypted=false,unencrypted=false;walk(d,o=>{Object.keys(o).forEach(k=>{if(k.toLowerCase()!=='volumes')return;const v=o[k],arr=Array.isArray(v)?v:(v&&typeof v==='object'?Object.keys(v).map(x=>v[x]):[]);arr.forEach(vol=>{if(!vol||typeof vol!=='object')return;const method=Number(vol.encryptionMethod!=null?vol.encryptionMethod:vol.EncryptionMethod),status=Number(vol.volumeStatus!=null?vol.volumeStatus:vol.VolumeStatus),prot=Number(vol.protectionStatus!=null?vol.protectionStatus:vol.ProtectionStatus),driveType=Number(vol.driveType!=null?vol.driveType:vol.DriveType);if(driveType&&driveType!==3)return;if(isFinite(method)||isFinite(status)||isFinite(prot)){seen=true;if(method>0||status===1||status===2||status===4||prot===1||prot===2)encrypted=true;else if(method===0||status===0)unencrypted=true;}});});},0);if(!seen)return'unknown';return encrypted&&!unencrypted?'ok':(unencrypted?'bad':'unknown');}
function atomic(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp-'+process.pid;fs.writeFileSync(tmp,data,'utf8');fs.renameSync(tmp,file);}
(async()=>{if(!fs.existsSync(meshctrl))fail('meshctrl.js not found: '+meshctrl);try{const raw=await call();let parsed;try{parsed=JSON.parse(raw);}catch(e){fail('MeshCtrl output is not JSON: '+e.message);}const devices=arrayOf(parsed),telemetry={};let known=0,bad=0;devices.forEach(d=>{const id=idOf(d);if(!id)return;const enc=encryption(d),ident=pickIdentity(d);telemetry[id]={encryption:enc,biosSerial:ident.biosSerial||undefined,uuid:ident.uuid||undefined};if(enc!=='unknown'){known++;if(enc==='bad')bad++;}});const doc={version:1,generatedAt:new Date().toISOString(),source:'meshctrl listdevices --details --json',devices:devices.length,stats:{encryptionKnown:known,encryptionBad:bad},telemetry:telemetry};atomic(output,JSON.stringify(doc));console.log('[telemetry] wrote',output,'devices='+devices.length,'encryptionKnown='+known,'encryptionBad='+bad);}catch(e){fail(e.message);}})();
